---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-role
  namespace: ocp-pipelines
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["pipelines", "tasks", "pipelineruns", "runs", "pipelineresources", "taskruns","triggerbindings","triggertemplates", "eventlisteners"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-tekton-triggers-binding
  namespace: ocp-pipelines
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: tekton-triggers-role
  apiGroup: rbac.authorization.k8s.io
