apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-trigger
  namespace: ocp-pipelines
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: nginx-build-run- # Creates unique run names (e.g., nginx-build-run-abcde)
      spec:
        serviceAccountName: tekton-pipeline-sa
        pipelineRef:
          name: nginx-build-pipeline # References the pipeline defined earlier
        params:
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
          - name: git-revision
            value: $(tt.params.gitrevision)
          - name: image-repo
            value: "quay.io/your-org/nginx-app"
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: pipeline-pvc
---
